# 메인 설정 파일(데이터 경로, 모델 이름, 배치 사이즈 등등 세팅함)

# 기본값 설정
defaults:
  - data: default
  - model: efficientnet_b0
  - override hydra/job_logging: disabled # 로그 깔끔하게 보기
  - override hydra/hydra_logging: disabled # 하이드라 자체 로깅 비활성화

# 완디비 설정
wandb:
  project: "cv-team9"
  entity: "cv-team9"  
  name: "${model.name}-${now:%Y-%m-%d-%H-%M-%S}" # 실행 이름자동 생성(모델명-시간)

# 공통 학습 파라미터
train:
  seed: 42
  learning_rate: 1e-4
  num_epochs: 10